[PATH]
lstview=d:\develop\modelos\wrpt\
MDB=d:\develop\modelos\wrpt\
ERRO=d:\develop\modelos\log\usulog.mdb
DIC=d:\develop\modelos\DICION\DIC.mdb
IMG=d:\develop\modelos\DICION\
WRPT=d:\develop\modelos\wrpt\WRPT.MDB
APP=d:\develop\modelos\wrpt\
RPT=d:\develop\modelos\wrpt\
RTF=d:\develop\modelos\WDOC\
RELAT=d:\develop\modelos\wrpt\
ICONES=d:\develop\modelos\ICONES\
MANA5=d:\develop\modelos\mana5\
MANA5EMP=d:\develop\modelos\mana5\EMP00001\
MANA5CON=d:\develop\modelos\mana5\configur\
IMPREL=d:\develop\modelos\mana5\
IMGJPG=d:\develop\modelos\wrpt\

[VALORES]
ICM=18
PIS=1.65
CONFINS=7.60
VFERID=132.37
PISCON=S

;clientes aliquotas diferenciadas

[18]
TEM=SIM
PIS=1.65
CONFINS=7.60

[91]
TEM=SIM
PIS=1.65
CONFINS=7.60

[93]
TEM=SIM
ICM=0
PIS=0
CONFINS=0

[PRECOS]
MANUAL=S

[FOTOS]
CAMINHO=d:\develop\modelos\FINAL\FOTOS\
LOGON=d:\develop\modelos\RH\FOTOS0001\

[HELP]
CAMINHO=d:\develop\modelos\HELP\padrao.chm
ALTERADO=d:\develop\modelos\HELP\custo.txt

[WRPT]
CAMINHO=d:\develop\modelos\wrpt\

[MP01.DBF]
DRIVER=DBFCDX
CAMINHO=d:\develop\modelos\mana5\EMP00001\
NUMMAINTAINED=3
MAINTAIN0=MP01.CDX
INDEX0=CODIGO
TAG0=MP01-1
TAG1=MP01-2
INDEX1=NOME
TAG2=MP01-3
INDEX2=CODFOLHA

[VMARK.DBF]
CAMINHO=d:\develop\modelos\viabili\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=VMARK.CDX
INDEX0=SEQ
TAG0=SEQ

[FLUXO.DBF]
CAMINHO=d:\develop\modelos\viabili\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=FLUXO.CDX
INDEX0=NUMERO
TAG0=FLUXO-1

[MD05.DBF]
CAMINHO=d:\develop\modelos\cep\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=MD05.CDX
INDEX0=UFICMS
TAG0=MD05

[VIABILI.DBF]
CAMINHO=d:\develop\modelos\viabili\
DRIVER=DBFCDX
NUMMAINTAINED=4
MAINTAIN0=VIABILI.CDX
INDEX0=OV
INDEX1=DESENHO
INDEX2=PEDCLI
INDEX3=CODIGOINT
TAG0=OV
TAG1=DESENHO
TAG2=PEDCLI
TAG3=CODIGOIN

[VIABIII.DBF]
CAMINHO=d:\develop\modelos\viabili\
DRIVER=DBFCDX
NUMMAINTAINED=2
MAINTAIN0=VIABIII.CDX
INDEX0=STR(OV,8)+STR(ITEM,3)
MAINTAIN1=VIABIII.CDX
INDEX1=OV
TAG0=OVITEM
TAG1=OV

[VPORC.DBF]
CAMINHO=d:\develop\modelos\viabili\
DRIVER=DBFCDX
NUMMAINTAINED=3
MAINTAIN0=VPORC.CDX
INDEX0=OV
INDEX1=CODIGO
INDEX2=VIABILI
TAG0=OV
TAG1=CODIGO
TAG2=VIABILI

[VFORC.DBF]
CAMINHO=d:\develop\modelos\viabili\
DRIVER=DBFCDX
NUMMAINTAINED=3
MAINTAIN0=VFORC.CDX
INDEX0=OV
INDEX1=CODIGO
INDEX2=VIABILI
TAG0=OV
TAG1=CODIGO
TAG2=VIABILI

[ESP.DBF]
CAMINHO=d:\develop\modelos\viabili\
DRIVER=DBFCDX
NUMMAINTAINED=3
MAINTAIN0=ESP.CDX
MAINTAIN1=ESP.CDX
MAINTAIN2=ESP.CDX
INDEX0=OV
INDEX1=CODIGO
INDEX2=VIABILI
TAG0=OV
TAG1=CODIGO
TAG2=VIABILI

[ESC.DBF]
CAMINHO=d:\develop\modelos\viabili\
DRIVER=DBFCDX
NUMMAINTAINED=3
MAINTAIN0=ESC.CDX
MAINTAIN1=ESC.CDX
MAINTAIN2=ESC.CDX
INDEX0=OV
INDEX1=CODIGO
INDEX2=VIABILI
TAG0=OV
TAG1=CODIGO
TAG2=VIABILI

[ESF.DBF]
CAMINHO=d:\develop\modelos\viabili\
DRIVER=DBFCDX
NUMMAINTAINED=3
MAINTAIN0=ESF.CDX
MAINTAIN1=ESF.CDX
MAINTAIN2=ESF.CDX
INDEX0=OV
INDEX1=CODIGO
INDEX2=VIABILI
TAG0=OV
TAG1=CODIGO
TAG2=VIABILI

[ESO.DBF]
CAMINHO=d:\develop\modelos\viabili\
DRIVER=DBFCDX
NUMMAINTAINED=3
MAINTAIN0=ESO.CDX
MAINTAIN1=ESO.CDX
MAINTAIN2=ESO.CDX
INDEX0=OV
INDEX1=CODIGO
INDEX2=VIABILI
TAG0=OV
TAG1=CODIGO
TAG2=VIABILI

[VMS03.DBF]
CAMINHO=d:\develop\modelos\viabili\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=VMS03.CDX
INDEX0=OV
TAG0=OV

[VFMS03.DBF]
CAMINHO=d:\develop\modelos\viabili\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=VFMS03.CDX
INDEX0=OV
TAG0=OV


[ESPMS03.DBF]
CAMINHO=d:\develop\modelos\viabili\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=ESPMS03.CDX
INDEX0=OV
TAG0=OV

[ESFMS03.DBF]
CAMINHO=d:\develop\modelos\viabili\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=ESFMS03.CDX
INDEX0=OV
TAG0=OV

[ESOMS03.DBF]
CAMINHO=d:\develop\modelos\viabili\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=ESOMS03.CDX
INDEX0=OV
TAG0=OV

[ESCMS03.DBF]
CAMINHO=d:\develop\modelos\viabili\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=ESCMS03.CDX
INDEX0=OV
TAG0=OV

[ESPMS06.DBF]
CAMINHO=d:\develop\modelos\viabili\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=ESPMS06.CDX
INDEX0=OV
TAG0=OV
//MAINTAIN1=ESPMS06.CDX
//INDEX1=OV
//TAG1=OVTEMP

[ESFMS06.DBF]
CAMINHO=d:\develop\modelos\viabili\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=ESFMS06.CDX
INDEX0=OV
TAG0=OV

[ESOMS06.DBF]
CAMINHO=fd:\develop\modelos\viabili\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=ESOMS06.CDX
INDEX0=OV
TAG0=OV

[ESCMS06.DBF]
CAMINHO=d:\develop\modelos\viabili\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=ESCMS06.CDX
INDEX0=OV
TAG0=OV

[VMS06.DBF]
CAMINHO=d:\develop\modelos\viabili\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=VMS06.CDX
INDEX0=OV
TAG0=OV

[VFMS06.DBF]
CAMINHO=d:\develop\modelos\viabili\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=VFMS06.CDX
INDEX0=OV
TAG0=OV

[MUSER.DBF]
CAMINHO=d:\develop\modelos\mana5\configur\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=MUSER.CDX
INDEX0=USUARIO
TAG0=MUSER

[MUSERW.DBF]
CAMINHO=d:\develop\modelos\mana5\configur\
DRIVER=DBFCDX
NUMMAINTAINED=2
MAINTAIN0=MUSERW.CDX
INDEX0=CONTROLE
TAG0=MUSERW
INDEX1=ITEMENU+STRZERO(POSICAO,3)+POSTELA
TAG1=MUSERW-2


[MANERR.DBF]
CAMINHO=d:\develop\modelos\mana5\configur\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=MANERR.CDX
INDEX0=USUARIO+DTOS(DATA)
TAG0=MANERR

[CONFIGU.DBF]
CAMINHO=d:\develop\modelos\mana5\
DRIVER=DBFCDX
NUMMAINTAINED=0

[MANARQ.DBF]
CAMINHO=d:\develop\modelos\mana5\configur\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=MANARQ.CDX
INDEX0=ARQUIVO
TAG0=MANARQ

[MANARQ1.DBF]
CAMINHO=d:\develop\modelos\mana5\configur\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=MANARQ1.CDX
INDEX0=ARQUIVO+STR(ITEM,2)
TAG0=MANARQ1

[MP04.DBF]
CAMINHO=d:\develop\modelos\mana5\EMP000[ZZ]\
DRIVER=DBFCDX
NUMMAINTAINED=4
MAINTAIN0=MP04.CDX
INDEX0=TECNICO
TAG0=MP04-1
TAG1=MP04-2
INDEX1=NOMTEC
TAG2=MP04-3
INDEX2=CNUMERO
TAG3=MP04-4
INDEX3=TABTEC

[MP05.DBF]
CAMINHO=d:\develop\modelos\mana5\EMP00001\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=MP05.CDX
TAG0=MP05-1
INDEX0=CODIGO

[MS06.DBF]
DRIVER=DBFCDX
CAMINHO=d:\develop\modelos\mana5\EMP00001\
NUMMAINTAINED=1
MAINTAIN0=MS06.CDX
INDEX0=CODIGO+STR(SEQ,3)+STR(SSQ,3)
INDEX1=CODIGO
INDEX2=FERRAMEN
INDEX3=CODIGO+TIPFEC
INDEX4=STR(PF,8)+STR(SEQ,3)+STR(SSQ,3)
TAG0=MS06-1
TAG1=MS06-2
TAG2=MS06-3
TAG3=MS06-4
TAG4=MS06-5

[MD02.DBF]
DRIVER=DBFCDX
CAMINHO=d:\develop\modelos\mana5\EMP00001\
NUMMAINTAINED=4
MAINTAIN0=MD02.CDX
INDEX0=CODIGO+CODIGO1+DTOS(DATA)
TAG0=MD02-1
TAG1=MD02-2
INDEX1=DATA
TAG2=MD02-3
INDEX2=CODIGO
TAG3=MD02-4
INDEX3=<CODIGO+DTOS(DATA)

[MP02.DBF]
CAMINHO=d:\develop\modelos\mana5\EMP00001\
DRIVER=DBFCDX
NUMMAINTAINED=3
MAINTAIN0=MP02.CDX
INDEX0=CODIGO
TAG0=MP02-2
TAG1=MP02-2
INDEX1=NOME
TAG2=MP02-3
INDEX2=CODFOLHA

[MA01.DBF]
DRIVER=DBFCDX
CAMINHO=d:\develop\modelos\mana5\EMP00001\
NUMMAINTAINED=8
MAINTAIN0=MA01.CDX
INDEX0=NUMERO
TAG1=MA01-1
TAG1=MA01-2
INDEX1=COGNOME
TAG2=MA01-3
INDEX2=NOME
TAG3=MA01-4
INDEX3=CGC
TAG4=MA01-5
INDEX4=VENDEDOR+COGNOME
TAG5=MA01-6
INDEX5=SISCO
TAG6=MA01-7
INDEX6=CNUMERO
TAG7=MA01-8
INDEX7=CODIGOINT

[MS01.DBF]
DRIVER=DBFCDX
CAMINHO=d:\develop\modelos\mana5\EMP00001\
NUMMAINTAINED=5
MAINTAIN0=MS01.CDX
INDEX0=CODIGO+STR(FORNECEDO,5)+COMPRA
TAG0=MS01-1
TAG1=MS01-2
INDEX1=CODIGO
TAG2=MS01-3
INDEX2=CODIGO
TAG3=MS01-4
INDEX3=STR(FORNECEDO)+CODIGO
TAG4=MS01-5
INDEX4=FORNECEDO

[ETI.DBF]
DRIVER=DBFCDX
CAMINHO=d:\develop\modelos\mana5\EMP00001\
NUMMAINTAINED=1
MAINTAIN0=ETI.CDX
INDEX0=CODIGO
TAG0=ETI
TAG1=ETI-2
INDEX1=NOME

[MAIL.DBF]
CAMINHO=d:\develop\modelos\mail\
DRIVER=DBFCDX
NUMMAINTAINED=0
MAINTAIN0=
INDEX0=

[MAILPG.DBF]
CAMINHO=d:\develop\modelos\mail\
DRIVER=DBFCDX
NUMMAINTAINED=0
MAINTAIN0=
INDEX0=

[MAILERRO.DBF]
CAMINHO=d:\develop\modelos\mail\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=MAILERRO.CDX
INDEX0=ERRO
TAG0=MAILERRO

[MAILPARA.DBF]
CAMINHO=d:\develop\modelos\mail\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=MAILPARA.CDX
INDEX0=ERRO
TAG0=MAILPARA

[MT01.DBF]
DRIVER=DBFCDX
CAMINHO=d:\develop\modelos\mana5\EMP00001\
NUMMAINTAINED=3
MAINTAIN0=MT01.CDX
TAG0=MT01-1
INDEX0=CODIGO
TAG1=MT01-2
TAG2=MT01-3
INDEX1=NOME
INDEX2=STR(DIMX,9,2)+STR(DIMY,7,2)+STR(DIMZ,7,2)

[MU01.DBF]
DRIVER=DBFCDX
CAMINHO=d:\develop\modelos\mana5\EMP00001\
NUMMAINTAINED=3
MAINTAIN0=MU01.CDX
TAG0=MU01-1
INDEX0=CODIGO
TAG1=MU01-2
TAG2=MU01-3
INDEX1=NOME
INDEX2=STR(DIMX,9,2)+STR(DIMY,7,2)+STR(DIMZ,7,2)

[VPORC.DBF]
CAMINHO=d:\develop\modelos\viabili\
DRIVER=DBFCDX
NUMMAINTAINED=3
MAINTAIN0=VPORC.CDX
INDEX0=OV
INDEX1=CODIGO
INDEX2=VIABILI
TAG0=OV
TAG1=CODIGO
TAG2=VIABILI

[VFORC.DBF]
CAMINHO=d:\develop\modelos\viabili\
DRIVER=DBFCDX
NUMMAINTAINED=3
MAINTAIN0=VFORC.CDX
INDEX0=OV
INDEX1=CODIGO
INDEX2=VIABILI
TAG0=OV
TAG1=CODIGO
TAG2=VIABILI

[VIAREV.DBF]
CAMINHO=d:\develop\modelos\viabili\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=VIAREV.CDX
TAG0=VIAREV
INDEX0=OV

[MW05.DBF]
DRIVER=DBFCDX
CAMINHO=d:\develop\modelos\mana5\EMP00001\
NUMMAINTAINED=2
MAINTAIN0=MW05.CDX
TAG0=MW05-1
INDEX0=CODIGO
TAG1=MW05-2
INDEX1=NOME

[MW07.DBF]
DRIVER=DBFCDX
CAMINHO=d:\develop\modelos\mana5\EMP00001\
NUMMAINTAINED=2
MAINTAIN0=MW07.CDX
TAG0=MW07-1
INDEX0=CODIGO
TAG1=MW07-2
INDEX1=NOME
