[MPOINT]
MPOINT=P:\RH\mpoint\Listas\relogio[Z].mdb
SQL=Provider=SQLOLEDB.1;Password=SENHA;User ID=USUARIO;Persist Security Info=true;Initial Catalog=DMPAcesso_V100;Data Source=DIMEPTARIF\SQLEXPRESS
CONECCAO=Provider=SQLOLEDB.1;Password=SENHA;User ID=USUARIO;Persist Security Info=true;Initial Catalog=DMPAcesso_V100;Data Source=DIMEPTARIF\SQLEXPRESS
CAMINHO=d:\develop\modelos\folha\mpoint.EXE
;SQL=Provider=SQLNCLI.1;Password=SENHA;Persist Security Info=True;User ID=usuario;Initial Catalog=DMPAcesso_V100;Data Source=dimeptarif\SQLEXPRESS
;CONECCAO=Provider=SQLNCLI.1;Password=SENHA;Persist Security Info=True;User ID=usuario;Initial Catalog=DMPAcesso_V100;Data Source=dimeptarif\SQLEXPRESS
;_SQL=Provider=MSDASQL.1;Persist Security Info=False;Data Source=wrel
;_CONECCAO=Provider=MSDASQL.1;Persist Security Info=False;Data Source=wrel

[FOPTOREL]
CAMINHO=d:\develop\modelos\folha\FOPTOREL.EXE


[FOTOS]
LOGON=d:\develop\modelos\RH\FOTOS00[ZZ]\
FUNBMP=d:\develop\modelos\rh\bmp\[ZZ]\
FUNJPG=d:\develop\modelos\rh\fotos\FOTOS00[ZZ]\
FUNJPGCPF=d:\develop\modelos\rh\fotos\cpf\
FOTOSMDBCPF=d:\develop\modelos\rh\fotos\FMP04cpf.MDB
FOTOSMDB=d:\develop\modelos\PECAS\FMP04[ZZ].MDB

[MUSERW.DBF]
CAMINHO=d:\develop\modelos\mana5\configur\
DRIVER=DBFCDX
NUMMAINTAINED=2
MAINTAIN0=MUSERW.CDX
INDEX0=CONTROLE
TAG0=MUSERW
INDEX1=ITEMENU+STRZERO(POSICAO,3)+POSTELA
TAG1=MUSERW-2

[MP02.DBF]
CAMINHO=d:\develop\modelos\mana5\EMP00001\
DRIVER=DBFCDX
NUMMAINTAINED=3
MAINTAIN0=MP02.CDX
INDEX0=CODIGO
TAG0=MP02-2
TAG1=MP02-2
INDEX1=NOME
TAg2=MP02-3
INDEX2=CODFOLHA

[MP06.DBF]
CAMINHO=d:\develop\modelos\rh\rh\
DRIVER=DBFCDX
NUMMAINTAINED=2
MAINTAIN0=MP06.CDX
INDEX0=CODIGO
TAG0=MP06-1
TAG1=MP06-2
INDEX1=NOME

[RHESC.DBF]
CAMINHO=d:\develop\modelos\rh\rh\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=RHESC.CDX
INDEX0=CODIGO
TAG0=RHESC

[HELP]
CAMINHO=d:\develop\modelos\HELP\padrao.chm
ALTERADO=d:\develop\modelos\HELP\FOLHA.txt

[CUREMI.DBF]
CAMINHO=d:\develop\modelos\rh\rh\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=CUREMI.CDX
INDEX0=NUMERO
TAG0=CUREMI

[CUREMP.DBF]
CAMINHO=d:\develop\modelos\rh\rh\
DRIVER=DBFCDX
NUMMAINTAINED=2
MAINTAIN0=CUREMP.CDX
INDEX0=NUMERO
TAG0=CUREMP
TAG1=CUREMP-2
INDEX1=COGNOME


[CURSO.DBF]
CAMINHO=d:\develop\modelos\rh\rh\
DRIVER=DBFCDX
NUMMAINTAINED=3
MAINTAIN0=CURSO.CDX
TAG0=CURSO
INDEX0=CURSO
TAG1=CURSO-2
INDEX1=DESCUR
TAG2=CURSO-3
INDEX2=GRUPO+CURSO

[CIDCONV.DBF]
CAMINHO=d:\develop\modelos\cep\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=CIDCONV.CDX
TAG0=CIDORI
INDEX0=ESTADO+CIDORI

[MD10.DBF]
CAMINHO=d:\develop\modelos\cep\
DRIVER=DBFCDX
NUMMAINTAINED=4
MAINTAIN0=MD10.CDX
TAG0=MD10-1
INDEX0=UF+NOME
TAG1=MD10-2
INDEX1=INICEP
TAG2=MD10-3
INDEX2=CODIBGE
TAG3=MD10-4
INDEX3=CODIRRF


[PAISES.DBF]
CAMINHO=d:\develop\modelos\cep\
DRIVER=DBFCDX
NUMMAINTAINED=5
MAINTAIN0=PAISES.CDX
TAG0=PAISES1
INDEX0=ISO3166A
TAG1=PAISES2
INDEX1=ISO3166B
TAG2=PAISES3
INDEX2=NOME
TAG3=PAISES4
INDEX3=DDD
TAG4=PAISES5
INDEX4=BACEN


[ANATEL.DBF]
CAMINHO=d:\develop\modelos\cep\
DRIVER=DBFCDX
NUMMAINTAINED=3
MAINTAIN0=ANATEL.CDX
TAG0=ANATEL-1
INDEX0=CNLCOD+PREFIXO
TAG1=ANATEL-2
INDEX1=DDD+PREFIXO
TAG2=ANATEL-3
INDEX2=UF+PREFIXO

[WRPT]
CAMINHO=d:\develop\modelos\wrpt\

[MUSER.DBF]
CAMINHO=d:\develop\modelos\mana5\configur\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=MUSER.CDX
INDEX0=USUARIO
TAG0=MUSER

[FOPTOCON.DBF]
CAMINHO=d:\develop\modelos\folha\
DRIVER=DBFCDX
NUMMAINTAINED=0

[FOPTOVAL.DBF]
CAMINHO=d:\develop\modelos\folha\
DRIVER=DBFCDX
NUMMAINTAINED=0

[TABFALTA.DBF]
CAMINHO=d:\develop\modelos\folha\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=TABFALTA.CDX
TAG0=TABFALTA
INDEX0=CODIGO

[NOMESEXO.DBF]
CAMINHO=d:\develop\modelos\folha\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=NOMESEX.CDX
TAG0=NOME
INDEX0=NAME


[HORAS.DBF]
CAMINHO=d:\develop\modelos\folha\horas001\
DRIVER=DBFCDX
NUMMAINTAINED=4
MAINTAIN0=horas.CDX
TAG0=NUMERO 
INDEX0=NUMERO
TAG1=NOME
INDEX1=NOME
TAG2=SETNUM
INDEX3=STR(SETOR,4)+STR(NUMERO,8)
TAG4=SETNOM
INDEX4=STR(SETOR,4)+NOME

[FO_CBO.DBF]
CAMINHO=d:\develop\modelos\folha\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=FO_CBO.CDX
TAG0=FO_CBO
INDEX0=CODIGO

[FO_CBON.DBF]
CAMINHO=d:\develop\modelos\folha\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=FO_CBON.CDX
TAG0=FO_CBO
INDEX0=CODIGO

[FOPTOHOR.DBF]
CAMINHO=d:\develop\modelos\folha\
DRIVER=DBFCDX
NUMMAINTAINED=2
MAINTAIN0=FOPTOHOR.CDX
TAG0=FOPTOHOR
INDEX0=NUMERO
TAG1=FOPTOHOR2
INDEX1=CODIGO

[PATH]
APP=d:\develop\modelos\wrpt\
DIC=d:\develop\modelos\DICION\DIC.mdb
DRIVER=DBFCDX
ERRO=d:\develop\modelos\log\usulog.mdb
FOLHA=d:\develop\modelos\folha\
FOLHAEMP=d:\develop\modelos\folha\EMP000[ZZ]\
ICONES=d:\develop\modelos\ICONES\
IMG=d:\develop\modelos\DICION\
IMGJPG=d:\develop\modelos\wrpt\
IMPREL=d:\develop\modelos\mana5\
MAIL=d:\develop\modelos\mail\
MAN=d:\develop\modelos\folha\MAN\
MANA5=d:\develop\modelos\mana5\
MANA5CON=d:\develop\modelos\mana5\configur\
MANA5EMP=d:\develop\modelos\mana5\EMP00001\
MANA5EMZ=d:\develop\modelos\EMP000[II]\
MANARQ=FOLHAMAN
MANCAM=d:\develop\modelos\folha\
MANTEM=S
MDB=d:\develop\modelos\wrpt\
RECUEDIT=d:\develop\modelos\folha\WRPT\
RELAT=d:\develop\modelos\wrpt\
RPT=d:\develop\modelos\wrpt\
RTF=d:\develop\modelos\wrpt\
WRPT=d:\develop\modelos\wrpt\wrpt.sqlite
lstview=d:\develop\modelos\wrpt\

[CONFIGU.DBF]
CAMINHO=d:\develop\modelos\mana5\
DRIVER=DBFCDX
NUMMAINTAINED=0

[MP04.DBF]
CAMINHO=d:\develop\modelos\mana5\EMP000[ZZ]\
DRIVER=DBFCDX
NUMMAINTAINED=4
MAINTAIN0=MP04.CDX
INDEX0=TECNICO
TAG0=MP04-1
TAG1=MP04-2
INDEX1=NOMTEC
TAG2=MP04-3
INDEX2=CNUMERO
TAG3=MP04-4
INDEX3=TABTEC

[MP04A.DBF]
CAMINHO=d:\develop\modelos\mana5\EMP000[ZZ]\
DRIVER=DBFCDX
NUMMAINTAINED=2
MAINTAIN0=MP04A.CDX
INDEX0=TECNICO
INDEX1=CURSO
TAG0=TECNICO
TAG1=CURSO

[MP04C.DBF]
CAMINHO=d:\develop\modelos\mana5\EMP000[ZZ]\
DRIVER=DBFCDX
NUMMAINTAINED=2
MAINTAIN0=MP04C.CDX
INDEX0=TECNICO
INDEX1=CURSO
TAG0=TECNICO
TAG1=CURSO

[MAILPG.DBF]
CAMINHO=d:\develop\modelos\mail\
DRIVER=DBFCDX
NUMMAINTAINED=0
MAINTAIN0=
INDEX0=

[MAILERRO.DBF]
CAMINHO=d:\develop\modelos\mail\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=MAILERRO.CDX
INDEX0=ERRO
TAG0=MAILERRO

[MAILPARA.DBF]
CAMINHO=d:\develop\modelos\mail\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=MAILPARA.CDX
INDEX0=ERRO
TAG0=MAILPARA

[MAIL.DBF]
CAMINHO=d:\develop\modelos\mail\
DRIVER=DBFCDX
NUMMAINTAINED=0
MAINTAIN0=
INDEX0=

[MANERR.DBF]
CAMINHO=d:\develop\modelos\mana5\EMP00001\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=MANERR.CDX
INDEX0=USUARIO+DTOS(DATA)
TAG0=MANERR

[FUNCAO.DBF]
CAMINHO=d:\develop\modelos\folha\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=FUNCAO.CDX
TAG0=FUNCAO
INDEX0=CODIGO
TAG1=FUNCAO-2
INDEX1=NOME

[FO_CHIS.DBF]
CAMINHO=d:\develop\modelos\mana5\EMP000[ZZ]\
DRIVER=DBFCDX
NUMMAINTAINED=2
MAINTAIN0=FO_CHIS.CDX
INDEX0=NUMERO
INDEX1=NOME
TAG0=NUMERO
TAG1=NOME

[UNID.DBF]
CAMINHO=d:\develop\modelos\folha\
DRIVER=DBFCDX
NUMMAINTAINED=2
MAINTAIN0=UNID.CDX
INDEX0=CODIGO
INDEX1=NUMERO
TAG0=UNID-1
TAG1=UNID-2


[TREII.DBF]
CAMINHO=d:\develop\modelos\EMP000[II]\
DRIVER=DBFCDX
NUMMAINTAINED=2
MAINTAIN0=TREII.CDX
INDEX0=TREIN
TAG0=TREII
TAG1=TREII2
INDEX1=NUMFUN

[TREIN.DBF]
CAMINHO=d:\develop\modelos\EMP000[II]\
DRIVER=DBFCDX
NUMMAINTAINED=4
MAINTAIN0=TREIN.CDX
INDEX0=TREIN
TAG0=TREIN
TAG1=TREIN-2
INDEX1=CURSO
TAG2=TREIN-3
INDEX2=REFER
TAG3=TREIN-4
INDEX3=DATACUR


[MP05.DBF]
CAMINHO=d:\develop\modelos\mana5\EMP00001\
DRIVER=DBFCDX
NUMMAINTAINED=1
MAINTAIN0=MP05.CDX
TAG0=MP05-1
INDEX0=CODIGO


[MC01.DBF]
DRIVER=DBFCDX
CAMINHO=d:\develop\modelos\mana5\EMP00001\
NUMMAINTAINED=1
MAINTAIN0=MC01.CDX
INDEX0=NUMERO
TAG0=MC01-1


[MC02.DBF]
DRIVER=DBFCDX
CAMINHO=d:\develop\modelos\mana5\EMP00001\
NUMMAINTAINED=1
MAINTAIN0=MC02.CDX
INDEX0=NUMERO
TAG0=MC02-1


[MC03.DBF]
DRIVER=DBFCDX
CAMINHO=d:\develop\modelos\mana5\EMP00001\
NUMMAINTAINED=1
MAINTAIN0=MC03.CDX
INDEX0=NUMERO
TAG0=MC03-1

[MC04.DBF]
DRIVER=DBFCDX
CAMINHO=d:\develop\modelos\mana5\EMP00001\
NUMMAINTAINED=1
MAINTAIN0=MC04.CDX
INDEX0=NUMERO
TAG0=MC04-1

[MC05.DBF]
DRIVER=DBFCDX
CAMINHO=d:\develop\modelos\mana5\EMP00001\
NUMMAINTAINED=1
MAINTAIN0=MC05.CDX
INDEX0=NUMERO
TAG0=MC05-1


[MI02.DBF]
DRIVER=DBFCDX
CAMINHO=d:\develop\modelos\mana5\EMP00001\
NUMMAINTAINED=1
MAINTAIN0=MI02.CDX
INDEX0=CODIGO
TAG0=MI02-1

[MI03.DBF]
DRIVER=DBFCDX
CAMINHO=d:\develop\modelos\mana5\EMP00001\
NUMMAINTAINED=1
MAINTAIN0=MI03.CDX
INDEX0=CENTRO
TAG0=MI03-1

[EMAIL]
SERVER=
PORTA=
FROM=
USUARIO=
SENHA=
POP=

[FO_DIO]
d:\develop\modelos\folha\E[AAAA]

[FIM]
