// Origem: dosprn1 (DBFCDX)
Table "dosprn1" {
  Note: "Origem: dosprn1"
  "PR_NO" INTEGER [default: 0]
  "PR_NAME" VARCHAR(50)
  "INIT_PR" VARCHAR(50)
  "EXIT_PR" VARCHAR(40)
  "BOLD_ON" VARCHAR(40)
  "BOLD_OFF" VARCHAR(40)
  "UNDL_ON" VARCHAR(40)
  "UNDL_OFF" VARCHAR(40)
  "ENL_ON" VARCHAR(40)
  "ENL_OFF" VARCHAR(40)
  "ITAL_ON" VARCHAR(40)
  "ITAL_OFF" VARCHAR(40)
  "HIGH_ON" VARCHAR(40)
  "HIGH_OFF" VARCHAR(40)
  "LOW_ON" VARCHAR(40)
  "LOW_OFF" VARCHAR(40)
  "COND_ON" VARCHAR(40)
  "COND_OFF" VARCHAR(40)
  "NLQ_ON" VARCHAR(40)
  "NLQ_OFF" VARCHAR(40)
  "RESERV_ON" VARCHAR(40)
  "RESERV_OFF" VARCHAR(40)
  "GRAPH_DRIV" VARCHAR(20)
  "PAGE_LEN" INTEGER [default: 0]
  "HEAD_MARG" INTEGER [default: 0]
  "FOOT_MARG" INTEGER [default: 0]
  Indexes {
    PR_NAME [name: "DOSPRN"]
  }
}

// Origem: dosprn2 (DBFCDX)
Table "dosprn2" {
  Note: "Origem: dosprn2"
  "EMPRESA" VARCHAR(15)
  "IMPRESS" VARCHAR(14)
  "EMULA" VARCHAR(14)
  "INICIALIZA" VARCHAR(14)
  "C10PP" VARCHAR(14)
  "C12PP" VARCHAR(14)
  "CONDON" VARCHAR(14)
  "CONDOFF" VARCHAR(14)
  "SPCPRON" VARCHAR(14)
  "SPCPROFF" VARCHAR(14)
  "SETCHAR" VARCHAR(14)
  "MSTFNT" VARCHAR(14)
  "PRTSTYL" VARCHAR(14)
  "DRAFT" VARCHAR(14)
  "CARTA" VARCHAR(14)
  "L6PP" VARCHAR(14)
  "L8PP" VARCHAR(14)
  "L12PP" VARCHAR(14)
  "SPCLINE" VARCHAR(14)
  "SPCLINEA" VARCHAR(14)
  "NEGRON" VARCHAR(14)
  "NEGROFF" VARCHAR(14)
  "DWIDEON" VARCHAR(14)
  "DWIDEOFF" VARCHAR(14)
  "DHEIGON" VARCHAR(14)
  "DHEIGOFF" VARCHAR(14)
  "ENFATON" VARCHAR(14)
  "ENFATOFF" VARCHAR(14)
  "BOLDON" VARCHAR(14)
  "BOLDOFF" VARCHAR(14)
  "SUBSCRON" VARCHAR(14)
  "SUBSCROFF" VARCHAR(14)
  "ITALON" VARCHAR(14)
  "ITALOFF" VARCHAR(14)
  "SUPSCRON" VARCHAR(14)
  "SUPSCROFF" VARCHAR(14)
  "SUB1SCRON" VARCHAR(14)
  "SUB1SCROFF" VARCHAR(14)
  "SKPON" VARCHAR(14)
  "SKPOFF" VARCHAR(14)
  "UNIPRT" VARCHAR(14)
  "BIPRT" VARCHAR(14)
  "SVCURSOR" VARCHAR(14)
  "RTCURSOR" VARCHAR(14)
  "PGTAM" VARCHAR(14)
  "PGLIN" VARCHAR(14)
  "TABSTOP" VARCHAR(14)
  "MARGTOP" VARCHAR(14)
  "MARGBOTT" VARCHAR(14)
  "MARGLEFT" VARCHAR(14)
  "MARGRIGHT" VARCHAR(14)
  "MVABSVLOC" VARCHAR(14)
  "MVRELVLOC" VARCHAR(14)
  "MVABSHLOC" VARCHAR(14)
  "MVRELHLOC" VARCHAR(14)
  "INTCHSPHMI" VARCHAR(14)
  "C11PP" VARCHAR(14)
  "C13PP" VARCHAR(14)
  "C14PP" VARCHAR(14)
  "C16PP" VARCHAR(14)
  "C20PP" VARCHAR(14)
  "EXPAND01" VARCHAR(14)
  "EXPAND02" VARCHAR(14)
  "EXPAND03" VARCHAR(14)
  "EXPAND04" VARCHAR(14)
  Indexes {
    EMPRESA+IMPRESS [name: "DOSPRN2"]
  }
}

// Origem: dosprn3 (DBFCDX)
Table "dosprn3" {
  Note: "Origem: dosprn3"
  "NOME" VARCHAR(22)
  "C_10CPI" VARCHAR(20)
  "C_17CPI" VARCHAR(20)
  Indexes {
    NOME [name: "NOME"]
  }
}

