[PRGEXT]
DES01=&Winprn 01
DES02=w&Inprn 02
DES03=D&os Prn2
DES04=&PrFile
DES05=&TxtPrint
DES06=NoDosI&mp
DES07=&USBPRINT
DES08=&Nao Configurado
DES09=&Nao Configurado
DES10=&Nao Configurado
EXE01=d:\develop\modelos\dosprn\winprn
EXE02=d:\develop\modelos\dosprn\winprn2
EXE03=d:\develop\modelos\dosprn\dosprn
EXE04=d:\develop\modelos\dosprn\prfile
EXE05=d:\develop\modelos\dosprn\txtprint
EXE06=d:\develop\modelos\dosprn\dosprn2
EXE07=d:\develop\modelos\dosprn\nodosimp
EXE08=
EXE09=
EXE10=
PAR01=
PAR02=/ZS /S
PAR03=
PAR04=
PAR05=
PAR06=80 PRE/SEL/VER
PAR07=/SEL /T2
PAR08=
PAR09=
PAR10=
PRE01=
PRE02=
PRE03=
PRE04=
PRE05=
PRE06=
PRE07=
PRE08=
PRE09=
PRE10=
TEC01=87
TEC02=73
TEC03=68
TEC04=80
TEC05=84
TEC06=77
TEC07=0
TEC08=0
TEC09=0
TEC10=0

[PATH]
PRWIN=d:\develop\modelos\dosprn\
DOSPRNDBF=d:\develop\modelos\dosprn\
PDFFONTS=d:\develop\modelos\dosprn\

[EMAIL]
SERVER=
PORTA=
FROM=
USUARIO=
SENHA=
POP=
APP=C:\Program Files\Mozilla Thunderbird\thunderbird.exe 

[FIM]
